Create api express server
htmlacademy-nodejs/870515-typoteka-3 pull request #10
Opened 2021-09-19 22:48 UTC by Nemhis

2021-09-20 14:55 UTC, Krabaton requested changes

2021-09-20 14:55 UTC, Krabaton commented on src/service/cli/server.js
>    return JSON.parse(posts);
Лучше всегда оборачивать `JSON.parse(posts)` `try catch`

2021-09-20 14:55 UTC, Krabaton commented on src/service/cli/server.js
> +    app.use(express.json());
Поставь limits до 10 кб. По хорошему надо, так можно туда вроде по умолчанию 100 кб.
[link](http://expressjs.com/uk/api.html)

2021-09-22 00:09 UTC, Nemhis commented on src/service/cli/server.js
>    return JSON.parse(posts);
Не совсем понял, вызов функции `getMocks` ниже по коду обёрнут в try catch

2021-10-01 02:00 UTC, Krabaton commented on src/service/cli/server.js
>    return JSON.parse(posts);
Не увидел, тогда не надо было)

2021-10-01 02:00 UTC, merged