Module4 task1
htmlacademy-nodejs/870515-typoteka-3 pull request #11
Opened 2021-10-22 01:19 UTC by Nemhis

2021-10-22 09:37 UTC, Krabaton requested changes

2021-10-22 09:37 UTC, Krabaton commented on src/service/middleware/comment-exist-validator.js
> +  // Не хочется завязываться на порядок вызова middleware, поэтому продублировал код из article-exist-validator
Не очень понял можно подробнее, что не хочет и почему дублирование?

2021-10-22 09:37 UTC, Krabaton commented on package.json
> +    "nanoid": "3.1.28",
Если стоит последняя версия Ноды в этом пакете уже нет необходимости. [crypto.randomUUID](https://nodejs.org/dist/latest-v17.x/docs/api/crypto.html#cryptorandomuuidoptions)

2021-10-22 09:37 UTC, Krabaton commented on src/service/api/article.js
> +// блоке `use`. Например: app.use(`/articles/:articleId/comments`, route);
Вот тут тоже не очень понял, какая конкретная проблема перед нами стоит? Что не позволяет и почему? Уверен, что вынести можно все в отдельный модуль, но не до конца понимаю конкретику.

2021-10-22 09:37 UTC, Krabaton commented on src/service/api/article.js
> +      res
Это ошибка без return

2021-10-22 09:37 UTC, Krabaton commented on src/service/api/article.js
> +    res
Общий вопрос по модулю, это все ассинхронные операции? Где тогда async/await?

2021-10-22 09:37 UTC, Krabaton commented on src/service/api/search.js
> +      res
Это ошибка без return

2021-10-23 14:52 UTC, Nemhis commented on src/service/middleware/comment-exist-validator.js
> +  // Не хочется завязываться на порядок вызова middleware, поэтому продублировал код из article-exist-validator
Есть валидатор `article-exist-validator.js`, у него две задачи:
1. проверить существование поста по id
2. сохранить найденный пост в запрос, в целях производительности

Чтобы проверить наличие комментария, необходимо загрузить пост со всеми комментариями. Возможны два варианта:
1. Загружать пост в `comment-exist-validator.js`. Тут самый главный минус - дублируется код загрузки поста из `article-exist-validator.js`
2. Использовать `article-exist-validator.js` с сохранением поста в спец. переменную запроса, а в `comment-exist-validator.js` доставать этот пост и уже проверять только наличие комментария в нём. Тут самый главный минус в том, что middleware `comment-exist-validator.js` должна строго исполняться после  `article-exist-validator.js`, чтобы middleware

Я выбрал первый вариант, потому что завязываться на порядок вызова middleware не хочется. Также в будущем мы наверняка пойдём в базу в middleware `comment-exist-validator.js` и просто проверим наличие коммента по id в таблице. Изменения придётся вносить только в `comment-exist-validator.js`.

2021-10-23 15:01 UTC, Nemhis commented on package.json
> +    "nanoid": "3.1.28",
Круто, буду знать, правда сейчас 17 версия не lts
![image](https://user-images.githubusercontent.com/26406885/138561608-0b9f4431-227a-4ecb-b113-a1f35a975f6a.png)

2021-10-23 15:02 UTC, Nemhis commented on src/service/api/article.js
> +// блоке `use`. Например: app.use(`/articles/:articleId/comments`, route);
Тут я бы лучше голосом обсудил

2021-10-23 15:04 UTC, Nemhis commented on src/service/api/article.js
> +// блоке `use`. Например: app.use(`/articles/:articleId/comments`, route);
Записался на консультацию, остальные комменты поправлю

2021-10-29 12:42 UTC, merged