Module3 task1
htmlacademy-nodejs/870515-typoteka-3 pull request #7
Opened 2021-09-07 19:20 UTC by Nemhis

2021-09-07 19:25 UTC, Nemhis commented
Регистрация маршрута в роутере, а конкретно конструкция вида
```js
/ :id([0-9]+)
```
выглядит не очень, но если убрать валидацию `:id` регулярным выражением, то маршруты типа `/add` будут перекрываться маршрутом с дин. параметром. Поэтому валидация выглядит разумным решением, но если кто-то забудет добавить валидацию, то маршрут без динамического параметра перестанет работать.
Есть какие-то другие способы сделать это красивее ?

2021-09-08 01:23 UTC, Krabaton requested changes

2021-09-08 01:23 UTC, Krabaton commented on src/express/routes/articles-routes.js
> +routes.get(`/:id([0-9]+)`, (req, res) => res.send(`/articles/:id([0-9]+)`));
Не использхуем регулярки в маршрутах. Первое это долго, второе не всегда безопасно. Для валдиации данных от клиента есть куча библиотек.
1. [joi](https://github.com/sideway/joi)
2. [express-validator](https://github.com/express-validator/express-validator)
3. [yup](https://github.com/jquense/yup)

Пока можно было бы сделать просто
```
routes.get(`/:id`, (req, res) => res.send(`/articles/${req.params.id}`));
```

2021-09-08 22:48 UTC, Nemhis commented on src/express/routes/articles-routes.js
> +routes.get(`/:id([0-9]+)`, (req, res) => res.send(`/articles/:id([0-9]+)`));
Убрал, но вопрос в комментах к пулу актуален

2021-09-13 12:56 UTC, Krabaton commented on src/express/routes/articles-routes.js
> +routes.get(`/:id([0-9]+)`, (req, res) => res.send(`/articles/:id([0-9]+)`));
> Убрал, но вопрос в комментах к пулу актуален

Про какой пул идет речь?

2021-09-13 12:56 UTC, merged

2021-09-13 20:36 UTC, Nemhis commented on src/express/routes/articles-routes.js
> +routes.get(`/:id([0-9]+)`, (req, res) => res.send(`/articles/:id([0-9]+)`));
![image](https://user-images.githubusercontent.com/26406885/133152813-7a44a16b-85a6-4e6a-b2ad-a6c8d88e2d61.png)

2021-09-13 20:37 UTC, Nemhis commented on src/express/routes/articles-routes.js
> +routes.get(`/:id([0-9]+)`, (req, res) => res.send(`/articles/:id([0-9]+)`));
![image](https://user-images.githubusercontent.com/26406885/133152867-edae81c3-9f89-49ef-89c5-b3ed122103fb.png)